### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by borealsmith** [algolia/scout-extended#102]
Hi, 

On the following page 
https://www.algolia.com/doc/framework-integration/laravel/searching/client-side-search/

I believe this code will not work
 <ais-results>
           <template scope="{ result }">
               <div>
                   <h1>@{{ article.title }}</h1>
                   <h4>@{{ article.summary }}</h4>
               </div>
           </template>
        </ais-results>

You should probably use 
<h1>@{{ result.title }}</h1>
<h4>@{{ result.summary }}</h4>

Cheers,

**Comment by nunomaduro** [comment]
Thanks! Pull Request was made on the Algolia doc team repository.

**Comment by nunomaduro** [comment]
_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
