### ISSUE TITLE
Index record does not exist

### ISSUE THREAD

**Issue by NU-OnE** [algolia/scout-extended#104]
I get **'Index record does not exist'** when using  multiple models in one index (Aggregators). But searching directly with model works fine. Followed exactly as mention on the [documentation ](https://www.algolia.com/doc/framework-integration/laravel/advanced-use-cases/multiple-models-in-one-index/) with new laravel instance.

**Aggregator Class**
```
use Algolia\ScoutExtended\Searchable\Aggregator;
use App\Accommodation;
use App\Activity;
use App\TravelTip;

class Record extends Aggregator
{
    /**
     * The names of the models that should be aggregated.
     *
     * @var string[]
     */
    protected $models = [
        Accommodation::class,
        Activity::class,
        TravelTip::class,
    ];


}
```

**AppServiceProvider**
```
    public function boot()
    {
        Record::bootSearchable();
    }
```

**In Controller** 
```
$records = \App\Search\Record::search()->raw();
dd($records);
```

![image](https://user-images.githubusercontent.com/16491972/50582844-82403600-0e8b-11e9-8e19-e8860a51d316.png)

**Comment by nunomaduro** [comment]
Seems like the remote index doesn’t exist. Have you imported your records using ‘php artisan scout:import’ ?

**Comment by NU-OnE** [comment]
No i did not do that because i was pretty sure index are exist on the cloud. But now i did `php artisan scout:import` then tried again. 

It Works. Thank You very much
But may i know what the reason importing data again although they exist on cloud.

**Comment by nunomaduro** [comment]
Great!

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
