### ISSUE TITLE
No results returned when using with Laravel Nova

### ISSUE THREAD

**Issue by bakerkretzmar** [algolia/scout-extended#105]
When using Scout Extended with Laravel Nova, I'm not getting any results searching on a model resource page for a specific model.

Using `laravel/scout` and `algolia/algoliasearch-client-php:^1.27` [per the Scout docs](https://laravel.com/docs/5.7/scout#installation) everything works out of the box.

With `algolia/scout-extended` I get nothing—everything else is the same, I just uninstalled the two packages above and installed Scout Extended instead.

I can see the queries hitting Algolia, and they look the same, the only difference I can see in the responses is that with `scout` and `algoliasearch-client-php`, Algolia stores the `objectID` property as the primary key of the model, something like `"9"`. Scout Extended appears to store the `objectID` as the model name and primary key, like `"App\Model::9"`.

Is this because of some change between `algoliasearch-client-php` 1.x and 2? Or is it possibly an issue with Nova?

Thanks!

**Comment by bakerkretzmar** [comment]
Setting the `getScoutKey` method on the model makes no difference. Locally it returns the right key, but Algolia still sets `"App\Model::1"` as the `objectID`.

**Comment by nunomaduro** [comment]
Thanks for posting this. I will run a quick test tomorrow and get back to you.

**Comment by nunomaduro** [comment]
Just submitted an issue on: https://github.com/laravel/nova-issues/issues/1188

**Comment by nunomaduro** [comment]
@bakerkretzmar This issue will be fixed on the next release of Laravel Nova.

**Comment by nunomaduro** [comment]
This issue was being fixed on the version `v1.3.1` of Laravel Nova.

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
