### ISSUE TITLE
where() method not filtering query

### ISSUE THREAD

**Issue by diazgilberto** [algolia/scout-extended#108]
I'm trying to integrate algolia in a personal project. The table I'm indexing is the `patterns` table that has the `user_id` as `FK` and is included as one of the fileds I upload to algolia.

```php
class SearchController extends Controller
{
    public function show()
    {
        $search = request('q');
        $patterns = Pattern::search($search)->where('user_id', '=', Auth::user()->id)->get();
        // dd(Auth::user()->id);
        return view('search.index', ['patterns' => $patterns]);
    }
}
```

If I dump the `user_id` I get `1`. Intentionally I'm searching for something that doesn't belong to that user expecting to get nothing from algoia but I still get the record back. The record that I get back has the `user_id` 3. 

I'm not sure if I'm missing some setting in the algolia dashboard or the code is missing something.

I'm searching for the word `test` and is the only record that contains that word.

<img width="1037" alt="screen shot 2019-01-06 at 9 57 01 am" src="https://user-images.githubusercontent.com/9165819/50738446-a789b880-1199-11e9-9680-d1e3780ae9ba.png">

**Comment by diazgilberto** [comment]
I did ran `composer require algolia/scout-extended` and 
`php artisan vendor:publish --provider="Laravel\Scout\ScoutServiceProvider"`.

**Comment by nunomaduro** [comment]
Perfect. Now I need you to check if the record that haves the objectID `App\Pattern::17` is the exacly the record with the id `17` in your database.

**Comment by diazgilberto** [comment]
<img width="928" alt="screen shot 2019-01-06 at 12 29 17 pm" src="https://user-images.githubusercontent.com/9165819/50740063-c181c600-11ae-11e9-856e-3c8b8740e72c.png">

**Comment by nunomaduro** [comment]
@diazgilberto This is super weird. Can you try add a `dd($options);` on the line 135 of the file `Laravel\Scout\Engines\AlgoliaEngine` and perform a search? And tell me the results of the `dd`.

**Comment by diazgilberto** [comment]
`Laravel\Scout\src\Engines\AlgoliaEngine` instead?

**Comment by nunomaduro** [comment]
Exacly.

**Comment by diazgilberto** [comment]
<img width="287" alt="screen shot 2019-01-06 at 2 16 22 pm" src="https://user-images.githubusercontent.com/9165819/50741051-cac65f00-11bd-11e9-9897-57ab2dc7644c.png">

**Comment by nunomaduro** [comment]
Perfect. Now, remove the previous `dd`. And on the line 135 replace the current line by: `return dd($algolia->search($builder->query, $options));`. And tell the results.

**Comment by nunomaduro** [comment]
Exacly, but you told me that using this code, The result of the `$patterns` is a model with the user_id == 3 right?
```php
        $patterns = Pattern::search('test')->where('user_id', '=', 1)->get();
        dd($patterns);
```

**Comment by diazgilberto** [comment]
Collection is empty as expected utilizing your snippet and my code.

```php
$patterns = Pattern::search('test')->where('user_id', '=', 1)->get();
// or
$patterns = Pattern::search('test')->where('user_id', '=', Auth::user()->id)->get();

dd($patterns);
```

The problem should be when I render the view.

```vue
@extends('layout._base')

@section('content')
    <ais-index
        app-id="{{ config('scout.algolia.id') }}"
        api-key="{{ config('scout.algolia.public') }}"
        index-name="patterns"
        id="app"
        query="{{ request('q') }}"
    >
        <div class="row">
            <div class="col">
                <ais-results>
                    <template slot-scope="{ result }">
                        <div class="card">
                            <div class="card-header">
                                <a :href="result.path">
                                    <ais-highlight :result="result" attribute-name="name"></ais-highlight>
                                </a>
                            </div>
                            <div class="card-body">
                                <ais-highlight :result="result" attribute-name="description"></ais-highlight>
                            </div>
                        </div>
                        <p>
                        </p>
                    </template>
                </ais-results>
            </div>
            <div class="col-3">
                <div class="card mb-5">
                    <div class="card-header font-weight-bold">Search</div>
                    <div class="card-body">
                        <ais-input placeholder="Search patterns..." class="form-control" :autofocus="true"></ais-input>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">
                        Filter By Category
                    </div>
                    <div class="card-body">
                        <ais-refinement-list attribute-name="category"></ais-refinement-list>
                    </div>
                </div>
            </div>
        </div>
    </ais-index>
@endsection
```

**Comment by nunomaduro** [comment]
Ahah. You have been searching with `vue-instantsearch` this whole time. Since you are using client-side search, you just have to inspect your network to debug your problem.

**Comment by nunomaduro** [comment]
Otherwise you can address this issue with our `vue-instasearch` team : https://github.com/algolia/vue-instantsearch.

**Comment by diazgilberto** [comment]
Well, my initial search is server side. Even though the server side search returns the correct object, looks like `vue-instantsearch` is querying again when I pass `uery="{{ request('q') }}"`.

**Comment by diazgilberto** [comment]
Closing since `scout-extended` is behaving as expected and the problem resides somewhere else.

Thanks Nuno!!!

**Comment by nunomaduro** [comment]
Thanks! Since you are doing client side search you don't need the server side search.

Don't hesitate to check the docs of vue instasearch: https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/vue.

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀

**Comment by babacarcissedia** [comment]
This is next level support! Thanks @nunomaduro for your work!
