### ISSUE TITLE
Question: Indices per ENV

### ISSUE THREAD

**Issue by borealsmith** [algolia/scout-extended#119]
Hi, 

I was wondering if is possible to have different indices per environment and configure which index to use for a given environment via the .env file ?

Thank you.

**Comment by nunomaduro** [comment]
You mean this: https://www.algolia.com/doc/framework-integration/laravel/indexing/configure-index/?language=php#per-environment-index-name ?

**Comment by borealsmith** [comment]
Yes. Exactly that :).
Thank you for your reply and sorry for the inconvenience. I was definitely  overlooking the docs.

**Comment by nunomaduro** [comment]
No worries.

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
