### ISSUE TITLE
Config sync is working wrong

### ISSUE THREAD

**Issue by antongorodezkiy** [algolia/scout-extended#122]
Looks like config sync is working wrong.

For the `config/scout-records.php` like this:

```
'searchableAttributes' => [
    'ordered(make)',
    'title'
],
```

After syncing index settings with `php artisan scout:sync` I'm getting the following response in algolia backend search form - https://nimb.ws/ub1wrT

So in this case "make" field is not searchable, which I believe is wrong.

---

For the `config/scout-records.php` like this:

```
'searchableAttributes' => [
    'make',
    'title'
],
```

After syncing index settings with `php artisan scout:sync` I'm getting the following response in algolia backend search form - https://nimb.ws/oHhZQs

In this case "make" field is searchable.

In both cases "make" in "Searchable Attributes" section appears as "ordered".

**Comment by nunomaduro** [comment]
Thanks for reporting this.

There is no issue, the `ordered` function doesn't exist. Since `orderer` is the default behavior.

You can use `unordered(make)` if you want to have that attribute unorderer.

**Comment by antongorodezkiy** [comment]
Then I believe the only change is the change for the instructions in the comments in generated config file:

```
/*
    |--------------------------------------------------------------------------
    | Searchable Attributes
    |--------------------------------------------------------------------------
    |
    | Limits the scope of a search to the attributes listed in this setting. Defining
    | specific attributes as searchable is critical for relevance because it gives
    | you direct control over what information the search engine should look at.
    |
    | Supported: Null, Array
    | Example: ["name", "ordered(email)", "unordered(city)"]
    |
    */
```

https://github.com/algolia/scout-extended/blob/master/resources/views/config.blade.php#L15

**Comment by nunomaduro** [comment]
You are right, I am going to fix this now 👍

**Comment by nunomaduro** [comment]
Thanks! It's fixed now.

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
