### ISSUE TITLE
Index configuration file per environment

### ISSUE THREAD

**Issue by bhulsman** [algolia/scout-extended#123]
Let's assume we have an `articles` index and on our local machine we've set `SCOUT_PREFIX=dev_`. This is to prevent screwing up the indexes for our production environment. On production, we might have set the prefix to `prod_` or aren't using a prefix at all.

So to add our index configuration to version control we run `php artisan scout:optimize` and a `scout-dev-articles.php` configuration file will be generated.

However, this will not work for our production environment, which will effectively require a `scout-prod-articles.php` configuration file.

In response to: https://twitter.com/enunomaduro/status/1088459313964699655

**Comment by nunomaduro** [comment]
Thanks for bring this into our attention. I don't have time, at the moment, to think about a solution for this. Any ideas?

**Comment by bhulsman** [comment]
Maybe add an argument to `php artisan scout:optimize`, like `--prefix=prod_` to generate the configuration file for a specific prefix?

**Comment by nunomaduro** [comment]
It may be a good idea, could you add a Pull Request on that?

**Comment by bhulsman** [comment]
Sure, will do!

**Comment by bhulsman** [comment]
@nunomaduro So far I can think of three approaches;

1. Override the prefix set in configuration, before generating the config file. However that doesn't work. 

```
if ($this->hasOption('prefix')) {
    config(['scout.prefix' => $this->option('prefix')]);
}
```

2. Change the `$path` for generating the file, but checking that the file already exists would not work anymore. Besides that it's not a good solution.

3. In the end it all boils down to `searchableAs`, which is where the prefix is added. I'm not sure that changing it into allowing a custom prefix is the right way. I cannot think about anything besides adding an optional argument to change the prefix.

Any ideas to what direction I should take?

**Comment by nunomaduro** [comment]
The option 1 should work. Why you say that doesn't work?

**Comment by bhulsman** [comment]
Might be an issue with the tests, but I get this error:

```
1) Tests\Features\OptimizeCommandTest::testCreationOfLocalSettingsWithCustomPrefix                                            Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_1_Algolia_AlgoliaSearch_SearchClient: :initIndex('custom_users'). Either the method was unexpected or its arguments matched no expected argument list for this method
```

I added the code right before `foreach` in the `OptimizeCommand.php` file: https://github.com/algolia/scout-extended/blob/master/src/Console/Commands/OptimizeCommand.php#L46

**Comment by nunomaduro** [comment]
Show me the test.

**Comment by bhulsman** [comment]
Sure:

```
public function testCreationOfLocalSettingsWithCustomPrefix(): void
{
    factory(User::class)->create();

    $this->mockIndex(User::class, $this->defaults());

    Artisan::call('scout:optimize', ['searchable' => User::class, '--prefix' => 'custom_']);

    $this->assertLocalHas($this->local(), config_path('scout-custom-users.php'));
}
```

**Comment by nunomaduro** [comment]
You need also add this while creating the mockIndex:
```php
$prefix = config('scout.prefix');
config(['scout.prefix' => 'custom_']);
$this->mockIndex(User::class, $this->defaults());
config(['scout.prefix' => $preflix]);
```

Reason: The mock created is being created with the index without the custom prefix.

**Comment by tobz-nz** [comment]
I've been thinking - and I think its relevant to this issue - why are config files split out by env anyway?
Should you been using the same settings across your environments? I know I always do I want my local/staging/production env to have the same searchable & facet fileds for example. having to make those changes in each file seems redundant.

Personally I'd prefer a single config per index. Simply `scout-articles.php`

Thoughts?

**Comment by bhulsman** [comment]
Seems fine, if you can still keep the different prefixes for prod/dev etc. in the .env file. But I agree, configuration of searchable fields should be the same on both environments.

**Comment by royduin** [comment]
I'd like to hook on, I'm coming from https://github.com/algolia/laravel-scout-settings where I did `php artisan algolia:settings:backup "App\Product"` once to generate the configuration so I can version control it. In deployments I've `php artisan algolia:settings:push "App\Product"` to make sure any configuration changes are deployed to all environments. I didn't use the `--prefix` option because the configuration is the same on all environments.

With Scout Extended I can't do this anymore. The prefix is always included with `scout:sync`. I just want/need one config file `scout-products.php` for all environments.

**Comment by tobz-nz** [comment]
Totally this 👆
Only one version is needed - I will never (I don't think) want different configurations.
The whole point is to sync the configs so they are all the same. Currently a bunch of manual work is required to do this.

**Comment by bhulsman** [comment]
Fixes my issue too, as long as I can add a prefix to my .env file for separate development/production.

**Comment by nunomaduro** [comment]
Thanks for all this feedback folks! We are going to tackle this end of this month. 👌🏻

**Comment by tobz-nz** [comment]
Any news on this issue?

**Comment by ctyler-liquidfish** [comment]
I've created a [pull request](https://github.com/algolia/scout-extended/pull/222) to help with this issue.
To take advantage of this change, you'll override LocalSettingsRepository in your app:
```php
public $bindings = [
    \Algolia\ScoutExtended\Repositories\LocalSettingsRepository::class=>\App\Algolia\AlgoliaConfigPathFix::class,
];
```
```php
<?php

namespace App\Algolia;

use Algolia\AlgoliaSearch\SearchIndex;
use Algolia\ScoutExtended\Repositories\LocalSettingsRepository;
use Illuminate\Support\Str;

class AlgoliaConfigPathFix extends LocalSettingsRepository
{
    public function getPath(SearchIndex $index): string
    {
        // Wrapping the index name in getIndexSettingsName is the only change I've made - JCT 2020/02/04
        $name = str_replace('_', '-', $this->getIndexSettingsName($index->getIndexName()));

        $name = is_array($name) ? current($name) : $name;

        $fileName = 'scout-'.Str::lower($name).'.php';
        $settingsPath = config('scout.algolia.settings_path');

        if ($settingsPath === null) {
            return app('path.config').DIRECTORY_SEPARATOR.$fileName;
        }

        if (! $this->files->exists($settingsPath)) {
            $this->files->makeDirectory($settingsPath, 0755, true);
        }

        return $settingsPath.DIRECTORY_SEPARATOR.$fileName;
    }

    protected function getIndexSettingsName($indexName){
        $indexName = Str::after($indexName,config('scout.prefix'));
        $indexName = Str::before($indexName,'_'.app()->environment());
        return $indexName;
    }
}
```
I'm appending the environment as a suffix, hence the specifics of my getIndexSettingsName function, but you could modify it to match whatever your needs are.

**Comment by rasmuscnielsen** [comment]
Really wish `LocalSettingsRepository` wasn't final. 

I completely understand this package can't predict all use cases and takes a stance on configuring different files per environment. 
But marking classes as final prevents me from implementing a very simple solution myself while this PR is being worked out. 

For the time being that leaves me the only option to fork the repo and thereby miss out on future updates until this issue has been worked out, when the alternative would have been simply to override a single public method. 

I hope you'll consider merging #222 which allows for some more wiggle room.

**Comment by AAllport** [comment]
Bumping this. Would be really helpful, especially since I presume a lot of people wouldn't have the need for different index settings between (for example) Live & Stage

**Comment by chloelbn** [comment]
Hey everyone!

[In this previous PR](https://github.com/algolia/scout-extended/pull/135#issuecomment-660550388) we suggested 
 dynamically adding the SCOUT_PREFIX option while you run your desired command, that'd give you the flexibility of choosing any prefix for your different environments. Removing the final tag is definitely not what we want to do so we won't push foward this solution.

I'm closing this issue but feel free to reopen it if you need to discuss it again.

**Comment by AAllport** [comment]
Would a PR be accepted for having a config option to remove the prefix from the index configuration file?

**Comment by rasmuscnielsen** [comment]
@AAllport For our use-case the ability to ignore the prefix would solve the issue yes. The aim is to simply have a ie. `scout-articles.php` config file that applies to all environments.

**Comment by AAllport** [comment]
@chloelbn, can we consider re-opening, it seems like there's certainly a _need_ for it.
A similar case was presented for Horizon here laravel/horizon#438

**Comment by chloelbn** [comment]
Hi @AAllport and @rasmuscnielsen ! Sorry for the late response. Please feel free to submit the PR to have a default config file indeed! Have a good day everyone
