### ISSUE TITLE
Can't make it work - Throwing ErrorException

### ISSUE THREAD

**Issue by ChristianKuri** [algolia/scout-extended#124]
Versions:
Laravel Framework: 5.7.20
PHP: 7.2.9
Scout-extended: 1.1

I had a laravel/scout working fine but decided to upgrade and use scout-extended.

I followed the instructions and wasnt able to use it nor install it, it said there was an error because I already had laravel/scout installed and it used algolia/algoliasearch-client-php:^1.27 and scout-extended needed ^2.0.0.

I uninstalled laravel/scout and algolia/algoliasearch-client-php:^1.27, then installed algolia/scout-extended (which installed the required dependecies), then published the configuration file (which is the same that I had) and added the use Laravel\Scout\Searchable; to the models required.

Now everything should be working fine, but when I run php artisan scout:reimport I get the following error

```php
ErrorException: include(/home/vagrant/code/mysite/vendor/composer/../algolia/algoliasearch-client-php/src/AlgoliaSearch/Version.php): failed to open stream: No such file or directory in /home/vagrant/code/mysite/vendor/composer/ClassLoader.php:444
```

Could you help me get this working? Thanks!

**Comment by nunomaduro** [comment]
No worries. Checking this after my vacations, next Friday!

**Comment by nunomaduro** [comment]
@ChristianKuri @SPQRInc Are you still facing that issue?

```
ErrorException: include(/home/vagrant/code/mysite/vendor/composer/../algolia/algoliasearch-client-php/src/AlgoliaSearch/Version.php): failed to open stream: No such file or directory in /home/vagrant/code/mysite/vendor/composer/ClassLoader.php:444
```

**Comment by ChristianKuri** [comment]
```
Problem 1
    - Installation request for algolia/scout-extended ^1.2 -> satisfiable by algolia/scout-extended[v1.2.0].
    - algolia/scout-extended v1.2.0 requires algolia/algoliasearch-client-php ^2.0 -> satisfiable by algolia/algoliasearch-client-php[2.0.0, 2.0.0-RC, 2.0.0-alpha, 2.0.0-alpha.1, 2.0.0-alpha.2, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0] but these conflict with your requirements or minimum-stability.
```

I will uninstall laralel\scout and algoliasearch-client-php^1.27 and will post my results.

**Comment by nunomaduro** [comment]
@ChristianKuri Ok. Waiting 👍

**Comment by ChristianKuri** [comment]
It is working now, but is not listening to my toSearchableArray() function so its passing all the model data, will check whats happening, thanks.

**Comment by nunomaduro** [comment]
All good.

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
