### ISSUE TITLE
Searching for date time does not work

### ISSUE THREAD

**Issue by SPQRInc** [algolia/scout-extended#133]
Hello everybody,

I got an record with this value:

```
publish_on:	2019-01-30 17:40:11
```

Unfortunately I can not search for this:

```
App\Posts::search('Title')->where('publish_on', '<', now())->get();
```

```
App\Posts::search('Title')->where('publish_on', '<', now()->toDateTimeString())->get();
```

does not work, too.

This result is always empty.

**Comment by nunomaduro** [comment]
The published_on value must be a timestamp (int).

**Comment by SPQRInc** [comment]
Hi and thank you for your reply.

Okay - this was not clear for me, because there is this example in the  docs:

```
$articles = Article::search('Star Trek')->where('created_at', '>=', now()->subDays(7))->get();
```

(https://www.algolia.com/doc/framework-integration/laravel/searching/server-side-search/)


`now()->subDays(7)` is an instance of `Carbon`:
```
>>> now()->subDays(7);
=> Illuminate\Support\Carbon @1548621728 {#3218
     date: 2019-01-27 20:42:08.941950 UTC (+00:00),
   }
```
 
So is this correct? Can I compare a `timestamp` with an instance of `Carbon`?

**Comment by nunomaduro** [comment]
Yes. Unless you have modified the method “toSearchableArray”.

If yes, please don’t forget to apply $array = $this->transform($array);

**Comment by SPQRInc** [comment]
Hi,

`$this->transform($array);` did the trick. Thanks!

**Comment by nunomaduro** [comment]
Cool!

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
