### ISSUE TITLE
What is the purpose of searchable() on the Aggregator class?

### ISSUE THREAD

**Issue by mozammil** [algolia/scout-extended#149]
Hi @nunomaduro 

This is more of a question. I stumbled upon this on `Algolia\ScoutExtended\Searchable\Aggregator`.

```
/**
* {@inheritdoc}
*/
public function searchable(): void
{
    AggregatorCollection::make([$this])->searchable();
}

```

I am assuming it is used to make an Aggregator searchable. However, it can't be called directly as it throws an exception. I also can't seem to find where this is being used. 

On the other hand, it would seem like we already have a `makeAllSearchable()` static method that works with the underlying models of the Aggregator.

**Comment by nunomaduro** [comment]
Tasks to perform here:

1. Understand what happens when you call `searchable` or `makeAllSearchable` directly from an aggregator. If those methods can't be call directly, we should override them and thrown an custom exception.

**Comment by TomKlotzPro** [comment]
Hi @mozammil ! 
Thanks for reporting this. 

Can you send me the snippet of code you are writing in order to use searchable method. And the exception you get.

**Comment by mozammil** [comment]
Hey @TomKlotzPro, 

Sorry for the late reply. I posted this question a while ago. Apologies if I don't remember the exact details, but it would seem the abstract class `Aggregator` has two public methods `searchable()` and `unsearchable()` when called both throws an exception unlike the `makeAllSearchable()` static method.

**Comment by chloelbn** [comment]
Hey @mozammil,

Indeed, both the methods `searchable()` and `unsearchable()` are not meant to be called by themselves. They’re used in the event of updating / deleting an Aggregator. We will take your remark into consideration and add an `@internal` flag to make it clearer they are not supposed to be used publicly. Thanks for your question, I’m closing this issue now.
