### ISSUE TITLE
Create a playground

### ISSUE THREAD

**Issue by nunomaduro** [algolia/scout-extended#152]
This **goal** is perform a pull request on the https://github.com/algolia/api-clients-playground repository inside the `laravel-scout-extended` folder an Laravel Application with Scout Extended Installed on it.

People should be able to clone the project locally and start playing with Scout Extended easily.

**Comment by TomKlotzPro** [comment]
The playground was added here : https://github.com/algolia/api-clients-playground 

This issue can be closed. @nunomaduro
