### ISSUE TITLE
Current master branch sends  '_highlightResult', '_rankingInfo' to Algolia in updateJob

### ISSUE THREAD

**Issue by nunomaduro** [algolia/scout-extended#154]
This bug was introduced on https://github.com/algolia/scout-extended/pull/147. An `UpdateJob` will try to attach  '_highlightResult', '_rankingInfo' to an record. Code to reproduce:
```php
    $models = Article::search($query)->get();
    $models->searchable();
```

**Goal**: We need to think about attaching this information somewhere else.

**Comment by mozammil** [comment]
Hi nuno,

When I was working on this feature, I added the ranking information as an attribute on the model itself. 

However, it doesn’t make sense to put it there and switched it over to ScoutMetaData. 

If I may provide a suggestion: can’t we have a similar property like ScoutMetaData. Maybe call it AlgoliaMetaData? 

What do you think?

**Comment by nunomaduro** [comment]
Thansk for answering @mozammil.

We don't have control over the `Searchable` trait. Adding a attribute may don't work. Any other idea?

**Comment by mozammil** [comment]
Right. I'm not sure in this case. 

We could explicitly remove those keys (_rankingInfo, _highlightResult) if they are present in the scoutMetadata while updating the object. 

However, there might be a reason for someone to still want to index those keys, in which case, maybe they would need to explicitly add it as a model attribute before calling searchable?

What do you think?

**Comment by nunomaduro** [comment]
@julienbourdeau @rayrutjes Any sugesttions on this?

**Comment by rayrutjes** [comment]
I think that @mozammil's suggestion is fine as a first iteration.
It is very unlikely that someone would want to index `_rankingInfo`, `_highlightResult`, so always removing those if present makes sense.

Then only the day we have someone willing to index those fields I would think more about it?

**Comment by nunomaduro** [comment]
Sounds good. Thanks @rayrutjes for your input on this. @mozammil I am also fine with: ```
explicitly remove those keys (_rankingInfo, _highlightResult)
```
