### ISSUE TITLE
Aggregate searchableAs equivalent 

### ISSUE THREAD

**Issue by edwardsides** [algolia/scout-extended#159]
Is there are searchableAs equivalent for aggregates so we can separate local vs production like we do with models?

eg:
local_All
production_All

**Comment by nunomaduro** [comment]
@edwardsides Does not work out of the box?

**Comment by nunomaduro** [comment]
This is the code of the `searchableAs` in aggregators:
```php
    /**
     * Get the index name for the searchable.
     *
     * @return string
     */
    public function searchableAs(): string
    {
        return config('scout.prefix').str_replace('\\', '', Str::snake(class_basename(static::class)));
    }
```

So normally, it should take in consideration the defined `scout.prefix`: https://www.algolia.com/doc/framework-integration/laravel/indexing/configure-index/?language=php#custom-index-name.

**Comment by edwardsides** [comment]
Thanks @nunomaduro I will check it out this week.

**Comment by nunomaduro** [comment]
No worries, if you still have the issue fell free to ask to re-open this issue.

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
