### ISSUE TITLE
Undefined property: Illuminate\Cache\Events\KeyWritten::$minutes 

### ISSUE THREAD

**Issue by borealsmith** [algolia/scout-extended#169]
Hi, 
I am using Laravel 5.8 and Scout-extended 1.6. 

My Sentry reports shows that this line of code 

api-key="<?php echo e(Algolia\ScoutExtended\Facades\Algolia::searchKey(App\MyModel::class)); ?>"  

Generates this error

Notice: Undefined property: Illuminate\Cache\Events\KeyWritten::$minutes

Have I miss something in the packages configuration ?

Thank you very much.

**Comment by borealsmith** [comment]
` api-key="<?php echo e(Algolia\ScoutExtended\Facades\Algolia::searchKey(App\MyModel::class)); ?>"`

**Comment by nunomaduro** [comment]
Can you send me the full error stack trace?

**Comment by borealsmith** [comment]
Sure. Please see one example below. 

ErrorException: Undefined property: Illuminate\Cache\Events\KeyWritten::$minutes
#77 /vendor/laravel/telescope/src/Watchers/CacheWatcher.php(83): Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
#76 /vendor/sentry/sentry/src/ErrorHandler.php(194): Sentry\ErrorHandler::handleError
#75 /vendor/laravel/telescope/src/Watchers/CacheWatcher.php(83): Laravel\Telescope\Watchers\CacheWatcher::recordKeyWritten
#74 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Illuminate\Events\Dispatcher::Illuminate\Events\{closure}
#73 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(196): Illuminate\Events\Dispatcher::dispatch
#72 /vendor/laravel/framework/src/Illuminate/Cache/Repository.php(550): Illuminate\Cache\Repository::event
#71 /vendor/laravel/framework/src/Illuminate/Cache/Repository.php(218): Illuminate\Cache\Repository::put
#70 /vendor/algolia/scout-extended/src/Repositories/ApiKeysRepository.php(94): Algolia\ScoutExtended\Repositories\ApiKeysRepository::getSearchKey
#69 /vendor/algolia/scout-extended/src/Algolia.php(87): Algolia\ScoutExtended\Algolia::searchKey
#68 /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\Support\Facades\Facade::__callStatic
#67 /storage/framework/views/f3afb4752ea45d1f04f36b8b6f624e50408604a0.php(7): include
#66 /vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): Illuminate\View\Engines\PhpEngine::evaluatePath
#65 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\CompilerEngine::get
#64 /vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\View::getContents
#63 /vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View::renderContents
#62 /vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\View\View::render
#61 /storage/framework/views/0beaba6b97a68836bc843e1c7851ff8b728753c3.php(14): include
#60 /vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): Illuminate\View\Engines\PhpEngine::evaluatePath
#59 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\CompilerEngine::get
#58 /vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\View::getContents
#57 /vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View::renderContents
#56 /vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\View\View::render
#55 /vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\Http\Response::setContent
#54 /vendor/symfony/http-foundation/Response.php(202): Symfony\Component\HttpFoundation\Response::__construct
#53 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router::toResponse
#52 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(720): Illuminate\Routing\Router::prepareResponse
#51 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Router::Illuminate\Routing\{closure}
#50 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#49 /app/Http/Middleware/AjaxNotAllowed.php(19): App\Http\Middleware\AjaxNotAllowed::handle
#48 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#47 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#46 /vendor/elic-dev/laravel-site-protection/src/Http/Middleware/SiteProtection.php(37): ElicDev\SiteProtection\Http\Middleware\SiteProtection::handle
#45 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#44 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#43 /app/Http/Middleware/Language.php(20): App\Http\Middleware\Language::handle
#42 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#41 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#40 /vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Laravel\Passport\Http\Middleware\CreateFreshApiToken::handle
#39 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#38 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#37 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Middleware\SubstituteBindings::handle
#36 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#35 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#34 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
#33 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#32 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#31 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\View\Middleware\ShareErrorsFromSession::handle
#30 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#29 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(59): Illuminate\Session\Middleware\StartSession::handle
#27 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#26 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#25 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
#24 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#23 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#22 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Cookie\Middleware\EncryptCookies::handle
#21 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#20 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#19 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline::then
#18 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Routing\Router::runRouteWithinStack
#17 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router::runRoute
#16 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router::dispatchToRoute
#15 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router::dispatch
#14 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
#13 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#11 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#10 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#9 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#8 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#7 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#6 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::handle
#5 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#4 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#3 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline::then
#2 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel::handle
#0 /public/index.php(53): null

ErrorException: Undefined property: Illuminate\Cache\Events\KeyWritten::$minutes (View: /home/forge/passapart.ovh/resources/views/layouts/main.blade.php)
#67 /vendor/laravel/telescope/src/Watchers/CacheWatcher.php(83): Illuminate\View\Engines\CompilerEngine::handleViewException
#66 /vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\View\Engines\PhpEngine::evaluatePath
#65 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\CompilerEngine::get
#64 /vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\View::getContents
#63 /vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View::renderContents
#62 /vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\View\View::render
#61 /storage/framework/views/0beaba6b97a68836bc843e1c7851ff8b728753c3.php(14): include
#60 /vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(43): Illuminate\View\Engines\PhpEngine::evaluatePath
#59 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\CompilerEngine::get
#58 /vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\View::getContents
#57 /vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View::renderContents
#56 /vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\View\View::render
#55 /vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\Http\Response::setContent
#54 /vendor/symfony/http-foundation/Response.php(202): Symfony\Component\HttpFoundation\Response::__construct
#53 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router::toResponse
#52 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(720): Illuminate\Routing\Router::prepareResponse
#51 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Router::Illuminate\Routing\{closure}
#50 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#49 /app/Http/Middleware/AjaxNotAllowed.php(19): App\Http\Middleware\AjaxNotAllowed::handle
#48 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#47 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#46 /vendor/elic-dev/laravel-site-protection/src/Http/Middleware/SiteProtection.php(37): ElicDev\SiteProtection\Http\Middleware\SiteProtection::handle
#45 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#44 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#43 /app/Http/Middleware/Language.php(20): App\Http\Middleware\Language::handle
#42 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#41 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#40 /vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Laravel\Passport\Http\Middleware\CreateFreshApiToken::handle
#39 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#38 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#37 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Middleware\SubstituteBindings::handle
#36 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#35 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#34 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
#33 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#32 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#31 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\View\Middleware\ShareErrorsFromSession::handle
#30 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#29 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(59): Illuminate\Session\Middleware\StartSession::handle
#27 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#26 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#25 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
#24 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#23 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#22 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Cookie\Middleware\EncryptCookies::handle
#21 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#20 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#19 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline::then
#18 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Routing\Router::runRouteWithinStack
#17 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router::runRoute
#16 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router::dispatchToRoute
#15 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router::dispatch
#14 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
#13 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#11 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#10 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#9 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#8 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#7 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#6 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::handle
#5 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#4 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#3 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline::then
#2 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel::handle
#0 /public/index.php(53): null

ErrorException: Undefined property: Illuminate\Cache\Events\KeyWritten::$minutes (View: /home/forge/passapart.ovh/resources/views/layouts/main.blade.php) (View: /home/forge/passapart.ovh/resources/views/layouts/main.blade.php)
#61 /vendor/laravel/telescope/src/Watchers/CacheWatcher.php(83): Illuminate\View\Engines\CompilerEngine::handleViewException
#60 /vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\View\Engines\PhpEngine::evaluatePath
#59 /vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\CompilerEngine::get
#58 /vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\View\View::getContents
#57 /vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\View\View::renderContents
#56 /vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\View\View::render
#55 /vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\Http\Response::setContent
#54 /vendor/symfony/http-foundation/Response.php(202): Symfony\Component\HttpFoundation\Response::__construct
#53 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router::toResponse
#52 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(720): Illuminate\Routing\Router::prepareResponse
#51 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Router::Illuminate\Routing\{closure}
#50 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#49 /app/Http/Middleware/AjaxNotAllowed.php(19): App\Http\Middleware\AjaxNotAllowed::handle
#48 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#47 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#46 /vendor/elic-dev/laravel-site-protection/src/Http/Middleware/SiteProtection.php(37): ElicDev\SiteProtection\Http\Middleware\SiteProtection::handle
#45 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#44 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#43 /app/Http/Middleware/Language.php(20): App\Http\Middleware\Language::handle
#42 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#41 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#40 /vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Laravel\Passport\Http\Middleware\CreateFreshApiToken::handle
#39 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#38 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#37 /vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Middleware\SubstituteBindings::handle
#36 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#35 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#34 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken::handle
#33 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#32 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#31 /vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\View\Middleware\ShareErrorsFromSession::handle
#30 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#29 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(59): Illuminate\Session\Middleware\StartSession::handle
#27 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#26 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#25 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::handle
#24 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#23 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#22 /vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Cookie\Middleware\EncryptCookies::handle
#21 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#20 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#19 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline::then
#18 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Routing\Router::runRouteWithinStack
#17 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router::runRoute
#16 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router::dispatchToRoute
#15 /vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router::dispatch
#14 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\Kernel::Illuminate\Foundation\Http\{closure}
#13 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#12 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#11 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#10 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#9 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Foundation\Http\Middleware\TransformsRequest::handle
#8 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#7 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#6 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::handle
#5 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Pipeline\Pipeline::Illuminate\Pipeline\{closure}
#4 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Pipeline::Illuminate\Routing\{closure}
#3 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline::then
#2 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Foundation\Http\Kernel::sendRequestThroughRouter
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel::handle
#0 /public/index.php(53): null

**Comment by nunomaduro** [comment]
You need to update your telescope package: https://github.com/laravel/telescope/issues/563.

**Comment by borealsmith** [comment]
Thank you very very much.
