### ISSUE TITLE
Command scout:reimport requires use of scout.prefix config to work as intended

### ISSUE THREAD

**Issue by sgilberg** [algolia/scout-extended#195]
I just installed scout-extended in an app that previously had Scout installed. Per the installation instructions, I ran `php artisan scout:reimport "App\MyModel" locally to regenerate the index. At the end of the process, it stated that all records were imported successfully, however the index was empty! I tried running it a second time, this time attempting to monitor progress in my Algolia dashboard, and I noticed that it had created a temp_ prefixed index, but all the records were being added directly to the original index instead of this temp_ index. This explains why I had an empty index: the temp_ index was empty and was being copied over the original. This behavior does not follow the stated zero-downtime intent. 

Digging into the ReImportCommand code, I noticed that it relies on the setting of scout.prefix in the config:
https://github.com/algolia/scout-extended/blob/294671edfdf3a7f93592c904019c077218b014c7/src/Console/Commands/ReImportCommand.php#L79-L84

This assumes that config('scout.prefix') is being used in the searchableAs() method of the model. It is set that way by default in the Searchable trait, but that method can be overridden in the model. My implementation was, in fact, overriding this method, and opting not to use the prefix.

I didn't want to label this as a bug, as there is currently a workaround (namely, always prepending with config('scout.prefix') in the searchableAs() method, even if that prefix is set as an empty string). However, I think an ideal setup would allow for this scenario out of the box. If that's not possible, I would recommend including a warning to this effect in the documentation, as the effects can be quite serious.

**Comment by chloelbn** [comment]
Hello,

Thanks for reporting this issue!

So we can better understand what's going on and dig into this together, could you to give us reproducible steps, as well as a code snippet of your model for example, or anything that could be of relevance to reproduce your issue?

Looking forward for your reply,

**Comment by sgilberg** [comment]
Thanks @chloelbn, here's a redacted snippet of my model:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MyModel extends Model
{
    public function searchableAs()
    {
        return 'my_custom_index_name'; // <-- This is where the problem lies, when not using config('scout.prefix') in the custom index name
    }

    public function toSearchableArray()
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
        ];
    }
}
```

Reproducible steps:
1)  Populate 'my_custom_index_name' index from existing model instances
2) Run `php artisan scout:reimport`
3) Check content of 'my_custom_index_name' (this would now be empty)

To fix:
1) Set SCOUT_PREFIX to blank string in .env
2) Update searchableAs() method above to:

```php
    public function searchableAs()
    {
        return config('scout.prefix').'my_custom_index_name'; // <-- This will now use the 'temp_' prefix as set in the ReimportCommand code quoted above
    }
```
3) Rerun `php artisan scout:reimport`
4) Check contents of 'my_custom_index_name' (this should now be restored to include all model instances)

**Comment by chloelbn** [comment]
Hi @sgilberg, thanks a lot for your quick answer! Could you confirm as well what you are using to populate 'my_custom_index_name' at first?

Have a good day,

**Comment by sgilberg** [comment]
Sure, it's an Algolia index, and I was populating it using the regular scout:import command before.

**Comment by chloelbn** [comment]
Hello @sgilberg, sorry for the delay. We are working on the issue right now and will keep you posted when we find a good solution. Thanks for your patience.

**Comment by jonathan-bird** [comment]
I've had a good thing about this after noticing this myself, and used @sgilberg's workaround.

I don't necessarily think this is a bug, but a design decision. If you think about how the prefix works and how the "reimport" command works, it adds "temp_" as a prefix to the index name, swaps it over, imports everything, and switches it back. 

For this to work, the index name needs to obviously point at whatever index has the complete data, even temporarily.

Maybe I'm missing something, but it seems that it's correctly designed, and just needs to be communicated in the docs that you can't just hard code the index name without the prefix.

I personally use a few things:

```
/**
     * Get the name of the index associated with the model.
     *
     * @return string
     */
    public function searchableAs(): string
    {
        return sprintf('%s%s_%s', config('scout.prefix'), self::SCOUT_INDEX, config('app.env'));
    }
```

**Comment by sgilberg** [comment]
Thanks @jonathan-bird! Maybe this issue would be better relabeled with the "Missing docs" label instead of "bug"? I see in the [docs](https://www.algolia.com/doc/framework-integration/laravel/indexing/configure-index/?client=php#custom-index-name) the example currently includes the prefix, but it still doesn't mention that this is a required piece if the reimport command is to work successfully.
