### ISSUE TITLE
Scout extended and repeated items

### ISSUE THREAD

**Issue by marcosdipaolo** [algolia/scout-extended#196]
I’m using Scout extended library which is great to split long records and avoid Algolia complaining about it. However the problem is when you search, say, the title of a post you get all the records od the diferent parts of that post. any way to filter that to avoid repeated matches?

**Comment by Haroenv** [comment]
Hi! You can use the [distinct](https://www.algolia.com/doc/api-reference/api-parameters/distinct/) feature to deduplicate items at query time. This works by configuring an attribute which will be the same for all records within the same group, and then at query time only retrieving one record of that collection.

**Comment by nunomaduro** [comment]
Exactly as @Haroenv said. You may want to check the docs on Laravel here on the topic distinct: https://www.algolia.com/doc/framework-integration/laravel/advanced-use-cases/split-large-records/?language=php

**Comment by marcosdipaolo** [comment]
OMG thanks a lot! I did not know that!
