### ISSUE TITLE
Retrieving facets and values

### ISSUE THREAD

**Issue by jrseliga** [algolia/scout-extended#197]
Is it possible to retrieve the facets and available values when executing a search similar to how the Instant Search component libraries work? 

```
Property::search('query')->get();
```

Looking over the documentation, it seemed like [with](https://www.algolia.com/doc/framework-integration/laravel/searching/server-side-search/?language=php#with) could be useful. e.g.

```
Property::search('query')->with([
    'facets' => ['beds', 'baths'];
])->get();
```

This doesn't seem to return that information though, is this information available using `with`?

If not it might be useful if the `Collection` that comes back from `->get()` included a `metadata` property that would hold this type of additional information about the result set returned from Algolia.

**Comment by nunomaduro** [comment]
You will need to use the method `raw`:

```php
$results = Property::search('query')->with([
    'facets' => ['beds', 'baths'];
])->raw();
```

The `$results` variable will contain all the information you need.
