### ISSUE TITLE
Package requirements and compatibility

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/scout-extended#2]
Currently, the project requires at least Laravel 5.7 (the latest). We need to define what version we want to be compatible with.

We need to fix the version of Scout we want to support (which will also define the PHP version).

Things to consider:

* Laravel Scout was release with Laravel 5.4
* Laravel 5.4 and Scout < 4.0 support php 5.6
* `getScoutKey` was introduced in 4.x (great feature)

**Comment by nunomaduro** [comment]
The version `v1.0.0` is has been tagged. The requirements are:

- Laravel Scout > 6
- Laravel > 5.6
- PHP 7.1.3
