### ISSUE TITLE
[bug] Passing an empty array to ->whereIn() ignores the whole statement

### ISSUE THREAD

**Issue by bkilshaw** [algolia/scout-extended#200]
If you pass an empty array as the second argument in a `->whereIn()` the whole statement appears to be ignored.

```
App\Model::search($query)->whereIn('author_id', [])->get()
```

I would expect that to return no results, since there's nothing being passed in. However, in practice it ignores it completely and returns the same results as `App\Model::search($query)->get()`

**Comment by nunomaduro** [comment]
Do you think you can work in a pull request on this?

**Comment by VinceG** [comment]
@nunomaduro We just saw this issue come up, this can potentially cause issues if not taken seriously since the condition is ignored and all results matching the criteria are returned. in some cases, a user might see more than they should.

I've created a PR for this with a test case. #265

**Comment by DevinCodes** [comment]
Thank you for the PR @VinceG, I'll take a look soon!
