### ISSUE TITLE
Where method only allows numbers

### ISSUE THREAD

**Issue by pdellepiane** [algolia/scout-extended#203]
I'm getting the following error: Invalid syntax for numeric condition

This is because on the "where" comparison is trying to parse an integer and I have a string.

My IDs are tokens so they are a mix of numbers and letters.

Is there a way out of this?

**Comment by nunomaduro** [comment]
To confirm, the `where` method in Scout (Laravel) and Scout-Extended (Algolia) is used for numeric comparison as stated in each of these sections:

- https://laravel.com/docs/5.8/scout#where-clauses
- https://www.algolia.com/doc/framework-integration/laravel/searching/server-side-search/?language=javascript#where

So it is indeed a syntax error to compare attributes that are not numeric. (i.e null or a string value)

Passing the filters key to the `with` method included with Scout Extended provides the functionality that you are looking for and accepts all other API parameters as well:

```php
$searchResults = App\Product::search($request->query('foo')) 
  ->with([
      'filters' => 'description:test'
    ]) 
  ->get();
```

Note that each attribute you use in filters **must be (defined as a facet)[https://www.algolia.com/doc/api-reference/api-parameters/attributesForFaceting/)**.
