### ISSUE TITLE
Not possible to access meta data of Aggregator without creating extra indice

### ISSUE THREAD

**Issue by tomworks** [algolia/scout-extended#206]
Hi

Trying to access Scout Meta Data not possible without creating an extra index, as per:

https://discourse.algolia.com/t/server-side-search-meta-data-not-accessible/8690/2

When using an aggregator, and try and access meta data of model, need to add the Searchable trait to the model. However this then means an extra indice is created on that model, in addition to the already established aggregated indice.

Is there any way to avoid this currently?

Thanks

Tom

**Comment by nunomaduro** [comment]
Humm, can you try adding this code to the model you added the `Searchable` trait but you don't want to be serchable:
```php
public function shouldBeSearchable()
{
    return false;
}
```

**Comment by tomworks** [comment]
Ok so that kind of works. I added shouldBeSearchable as false to models that are aggregated. The import command says it is creating extra indices and adding records. However it actually only creates the extra indice it doesn't add the records. So although not perfect that is workable.

**Comment by nunomaduro** [comment]
To be honest, I think that is an advanced usage. If more people have that need, we add the docs.
