### ISSUE TITLE
[Bug] Loading all files in app()->path() will cause errors when dependencies aren't loaded

### ISSUE THREAD

**Issue by georgeboot** [algolia/scout-extended#213]
Consider the following code from this repo: https://github.com/algolia/scout-extended/blob/ea5cec58af8f726fe1f5848082c0a5f84ffbd3b8/src/Helpers/SearchableFinder.php#L97-L101

In practice, this will load all `*.php` files . in your `app/` directory.

We have some service providers (e.g. `app/Providers/TelescopeServiceProvider`) that only load when on local. These classes depend on `laravel/telescope` to be installed via composer. Because these packages are a `--dev` requirement, they won't be installed in production.

However, because this piece of code is trying to load all files, php needs to be able to resolve the dependencies these files depend on. In the case of my `app/Providers/TelescopeServiceProvider`, this fails because `laravel/telescope` isn't installed in production:

```
In TelescopeServiceProvider.php line 10:
                                                                           
  Class 'Laravel\Telescope\TelescopeApplicationServiceProvider' not found  
```

I'm not sure what would be the best way to resolve this. Silence errors? Add a blacklist to ignore certain classes from being loaded?

**Comment by nunomaduro** [comment]
Humm. I good fixed for those, would be show a warning on the class about this specific class. Can you pull request that?

Meanwhile, just be specify on your searchables: `php artisan command --searchable=model`.

**Comment by georgeboot** [comment]
See #214

**Comment by georgeboot** [comment]
This should be reopened as the issue still exists.

I see my PR didn't work on 7.2 and 7.3 (completely missed that, sorry!) and @nunomaduro  tried but ended up reverting the PR.

What would you suggest is the best approach now?

**Comment by FreekVR** [comment]
Just came here after encountering the same issue on prod and staging with Telescope, like in the OP. Are there any other workarounds except having to specify all my searchables in the CLI?

**Comment by ametad** [comment]
Might I suggest an approach we used, as we had a similar problem?

Outlined in this class: https://github.com/matchish/laravel-scout-elasticsearch/blob/3ac43a86b46aa507e81e7c448c12cccd6317fd40/src/Searchable/SearchableListFactory.php#L22

Spoiler: it parses php and not load it.

**Comment by DevinCodes** [comment]
Hey @georgeboot,

Sorry that this has been stale for a while. The good thing about that (I suppose) is that this package has dropped support for `php < 7.3`, which means that your changes should work. Could you please try to recreate your PR with the latest changes of the `master` branch?

Thank you in advance, let me know if I can be of any help 😄
