### ISSUE TITLE
Multiple algolia app ids in one Laravel setup

### ISSUE THREAD

**Issue by larsboldt** [algolia/scout-extended#232]
How do I use different Algolia app ids for different models? We have one API supporting multiple sites and per Algolia rules one needs to split sites into different app spaces.

Using Laravel 7

**Comment by nunomaduro** [comment]
We currently don't support that feature.

You may need to use to PHP Client directly to accomplish something like that: https://www.algolia.com/doc/api-client/getting-started/install/php/.
