### ISSUE TITLE
Instantiate LengthAwarePaginator from the container

### ISSUE THREAD

**Issue by memdev** [algolia/scout-extended#233]
When using the Builders `paginate()` method, the pagination classes (Paginator, LengthAwarePaginator) are instantiated directly and therefore are not swappable.

It should be instantiated using the DI container.

**Comment by nunomaduro** [comment]
Can you point me to the file and line?

**Comment by memdev** [comment]
File (namespace): `Laravel\Scout\Builder`

Lines: 265, 273, 293, 299
(both `paginate` methods)

**Comment by memdev** [comment]
Aww, sorry. I just realized it is not a scout-extended issue, but scout itself...

**Comment by nunomaduro** [comment]
No problem. Fell free to create an issue there.
