### ISSUE TITLE
Missing docs regarding required index permission

### ISSUE THREAD

**Issue by rasmuscnielsen** [algolia/scout-extended#236]
Hey there - thanks for this awesome package

For anyone else encountering a 403 error upon running `php artisan scout:optimize`, please beware it might be due to api key index restriction.

The error message will look something like:

```
  Algolia\AlgoliaSearch\Exceptions\BadRequestException 

  Index not allowed with this API key
```

Scout extended needs access to an extra temp index: `temp-laravel-scout-extended`. Without this permission it will fail with no other explanation given.

In my case the api key configuration now looks like:

![image](https://user-images.githubusercontent.com/8465957/82878864-620b8e00-9f3c-11ea-8020-84ae97f78ca2.png)

Hope this help someone else out there. It would be nice to have this written in the otherwise great documentation.

Cheers

**Comment by nunomaduro** [comment]
Thanks for reporting this issue, we going to perform a pull request on the documention.
