### ISSUE TITLE
[Question] Steps to contribute

### ISSUE THREAD

**Issue by lscortesc** [algolia/scout-extended#245]
#### How can configure my local setup to contribute to project?

I want to contribute to project but I'm have some issues to configure my local setup. Does exist any guide to configure the project? I'm using `php: ^7.4`

#### My steps

- I've forked the project
- I've installed the dependencies: `composer install`
- When I run `composer test` I have the follow error:
![image](https://user-images.githubusercontent.com/6760803/92801171-fe865e80-f37a-11ea-9cee-959d87e132d8.png)
- The `phpunit` tests aren't executed

#### Edit

I was able to solve the problem with `phpstan` by replacing `$this->app->path()` with `$this->app->basePath()` in the line https://github.com/algolia/scout-extended/blob/master/src/Helpers/SearchableFinder.php#L97 but I'm not sure if that it's correct.

When I run `composer phpunit:test` I have the follow error in multiple tests: `Algolia\AlgoliaSearch\Exceptions\UnreachableException: Impossible to connect, please check your Algolia Application Id`. 

I don't know if I should configure an Algolia App for testing because exists a Mock of `AlgoliaClient` in https://github.com/algolia/scout-extended/blob/master/tests/TestCase.php#L124

If I should configure my credentials of Algolia, where should I put them?

Thanks

**Comment by DevinCodes** [comment]
Hey there, thank you for wanting to participate in the development of Scout Extended, and sorry for the late reply.

To run _all_ the tests, you need to pass Algolia credentials indeed. During the test suite, we set up a basic Laravel application, and it uses the default Scout config. This means you need to make sure the `ALGOLIA_APP_ID` and `ALGOLIA_SECRET` variables are available in your environment. You can do this, for example, by running your tests like this:

```sh
ALGOLIA_APP_ID="yourAppID" ALGOLIA_SECRET="yourAdminAPIKey" composer test
```

Please note that the tests add records and perform operations on your application. While this shouldn't be a lot of operations, make sure you don't go over the limits of your plan.

I'll add this info to the contributing guidelines soon.
