### ISSUE TITLE
Does not work with the mysql driver

### ISSUE THREAD

**Issue by rabol** [algolia/scout-extended#266]
- Laravel version: 8.28.1
- Algolia Scout Extended version: 1.13
- Algolia Client Version: #.#.#
- Language Version: 7.4

### Description

Im using a mysql driver for scout and it works fine.
Then I was looking for a way to search from multiple models at the same time and saw scout-extended

### Steps To Reproduce

Install an new laravel app
install laravel scout
install this yab/laravel-scout-mysql-driver
install scout-extended

create 2 models
add the scout Searchable trait
test that i work

create aggregator

Add the two models to the aggregator class

then try to search:

TestSearch::search('test')->get();

Then I get the following error:

````
Call to undefined method class@anonymous/home/vagrant/code/backpack/vendor/algolia/scout-extended/src/Searchable/Aggregator.php:265$9c::toSearchableArray()
````

**Comment by DevinCodes** [comment]
Hi there!

[Scout Extended](https://www.algolia.com/doc/framework-integration/laravel/getting-started/introduction-to-scout-extended/?client=php) is made to work with the Algolia driver, and not other drivers that Scout provides. As the logic we add in our package is highly specific to using Algolia in your app, there's currently no plans to add support for the other drivers.

If you still want to use Aggregators, feel free to create a [free Algolia account](https://www.algolia.com/users/sign_up) and leverage all the features from Scout Extended.
