### ISSUE TITLE
Add join in selection

### ISSUE THREAD

**Issue by kossa** [algolia/scout-extended#276]
- Laravel version: v8.35.1
- Algolia Scout Extended version: v1.15.0
- Algolia Client Version: #.#.#
- Language Version: ??

### Description
I have posts table and custom_fields related to posts, How can I filter with custom_fields ?

**Comment by DevinCodes** [comment]
Algolia doesn't support JOIN operations across tables, you need to include all the data you want to filter on in your record. We elaborate on this on the [scout extended documentation](https://www.algolia.com/doc/framework-integration/laravel/indexing/configure-searchable-data/?client=php#relationships). Let me know if you still have any questions after reading this 🙂
