### ISSUE TITLE
Scout `lazyMap` method not implemented, returns no results

### ISSUE THREAD

**Issue by bakerkretzmar** [algolia/scout-extended#298]
- Laravel version: 8.81.0
- Algolia Scout Extended version: 2.0.0
- Algolia Client Version: 3.2.0
- Language Version: 8.1.2

### Description

Laravel Scout has a companion method to `map`, [`lazyMap`](https://github.com/laravel/scout/blob/3f2583f99afe9265c015e7f0d20a36347ce2510a/src/Engines/AlgoliaEngine.php#L215-L231), which uses a generator under the hood to keep memory usage low. That `lazyMap` method doesn't play nicely with Scout Extended, in basically the same way as the underlying issue in #279—it uses Algolia's `objectID` to retrieve models, which it expects to be the actual model key, but which with Scout Extended installed is actually something like `App\Event::20`.

The `map` method does this too, but Scout Extended overrides it and accounts for the primary key thing inside the `ModelsResolver` class.

I can't switch to using the `map` method because the code calling `lazyMap` is inside Laravel Nova, in the global search code. I'll file an issue there too.

Ideally Scout Extended would also override `lazyMap`, with functionality similar to `map` but returning a generator or lazy collection if possible. I'll try to take a crack at a PR for that in the next week or two.

In the meantime, for anyone else running into this, I managed to work around it by overriding the `Laravel\Nova\Query\Builder` class:

```php
// In the `register` method of `app/Providers/NovaServiceProvider.php`

use App\Nova\Builder;
use Laravel\Nova\Contracts\QueryBuilder;

$this->app->bind(QueryBuilder::class, fn ($app, $parameters) => new Builder(...$parameters));

// `app/Nova/Builder.php`

use Illuminate\Support\LazyCollection;
use Laravel\Nova\Query\Builder as Nova;

class Builder extends Nova
{
    public function cursor()
    {
        $queryBuilder = $this->applyQueryCallbacks($this->queryBuilder);

        // Remove or comment out this part
        // if (method_exists($queryBuilder, 'cursor')) {
        //     return $queryBuilder->cursor();
        // }

        return LazyCollection::make(function () use ($queryBuilder) {
            yield from $queryBuilder->get()
                ->each(function ($result) {
                    yield $result;
                });
        });
    }
}
```

**Comment by DevinCodes** [comment]
Hi @bakerkretzmar ,

Thank you for reporting this. Feel free to assign me to your PR once it's open so I can review and release 🙂 

Cheers!
