### ISSUE TITLE
Add support for Laravel 9

### ISSUE THREAD

**Issue by eminos** [algolia/scout-extended#302]

**Comment by kabacs** [comment]
@eminos 

Was having also a problem with scout extended when upgrading to Laravel 9, did the following to resolve:

1. Remove algolia/scout-extended from composer.json
2. edit  laravel/framework to ^9.0
3. edit  nunomaduro/collision to ^6.0
4. replace facade/ignition with "spatie/laravel-ignition": "^1.0"
5. execute "composer update"
6. execute "composer require algolia/scout-extended"

In my case I also had also to remove fideloper/proxy from composer.json

**Comment by DevinCodes** [comment]
What composer errors did you both get? When trying to install Scout Extended into a new Laravel 9 project I have no issues (v2 of Scout Extended is supposed to work with Laravel 9).

Thank you in advance!

**Comment by kabacs** [comment]
@DevinCodes 

After just altering composer.json for Laravel upgrade (points 2-4), and then issuing the composer update command, I have the following output:

`Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install algolia/scout-extended v1.20.0 (conflict analysis result)
    - Conclusion: don't install algolia/scout-extended v1.20.1 (conflict analysis result)
    - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.1.1) does not satisfy that requirement.
    - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.1) does not satisfy that requirement.
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.1) does not satisfy that requirement.
    - Root composer.json requires algolia/scout-extended ^1.20 -> satisfiable by algolia/scout-extended[v1.20.0, v1.20.1, v1.x-dev].
    - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)
    - algolia/scout-extended v1.x-dev requires illuminate/support ^6.0|^7.0|^8.0 -> satisfiable by illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[v5.6.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^9.0 -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

**Comment by DevinCodes** [comment]
You can pin Scout Extended to `^2.0`, that should resolve your issue (or `composer require "algolia/scout-extended:^2.0"`)

**Comment by kabacs** [comment]
> You can pin Scout Extended to `^2.0`, that should resolve your issue (or `composer require "algolia/scout-extended:^2.0"`)

This solved the upgrade, it went without errors.

Thx @DevinCodes

**Comment by DevinCodes** [comment]
Happy coding! 😄
