### ISSUE TITLE
Support meilisearch?

### ISSUE THREAD

**Issue by mokhosh** [algolia/scout-extended#321]
I was checking out the code specifically for aggregators and it seemed like there isn't anything specific to Algolia.
Is it possible to add (at least partial) support for Meilisearch to this amazing package?

**Comment by DevinCodes** [comment]
Hi there!

This library was specifically designed to work with Algolia so it will likely break when using other search engines for Laravel Scout. There are currently no plans to support other engines in this package, we suggest using the Laravel Scout package directly.

Cheers!
