### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by mattmcdonald-uk** [algolia/scout-extended#340]
This package is currently preventing upgrading to Laravel 11.

Would be great to see the open PR (https://github.com/algolia/scout-extended/pull/339) to introduce Laravel 11 support merged.

**Comment by tecreasey** [comment]
Agreed. I am wanting to update a development project to Laravel 11.

**Comment by DevinCodes** [comment]
This has been released in [v3.1.0](https://packagist.org/packages/algolia/scout-extended#v3.1.0)
