### ISSUE TITLE
Support of Laravel Nova

### ISSUE THREAD

**Issue by shirshak55** [algolia/scout-extended#58]
Yeah it will be awesome if we can manage index, its status, statistics etc directly from Nova admin panel. 

If dedicated tool like telescope is there it will be fine too. Yeah its easy to see from algolia but we cannot give access to everybody right like in admin panel we can have our own restrictions etc..

**Comment by shirshak55** [comment]
By the way thanks for creating such a good package. Algolia should be really happy about this package.

**Comment by nunomaduro** [comment]
@shirshak55 Any idea of the feature set of this? Any examples of other nova packages?

**Comment by shirshak55** [comment]
@nunomaduro  i think the feature we would like to see is like ability to do stuff on our admin panel instead of going to algolia.com . Statistics data on our admin panel etc. 

By the way nova is not opensource so i don't think it will have advantage to many people so its ur choice 👍

**Comment by nunomaduro** [comment]
It's a good idea, but no plans for this at the moment. 👍

**Comment by shirshak55** [comment]
Yea its fine I also stopped using Laravel Nova :D
