### ISSUE TITLE
Aggregates unable to rehyrdate models if scout key is set

### ISSUE THREAD

**Issue by jimbojsb** [algolia/scout-extended#66]
I've not fully investigated the source of this yet, but it appears that if the scoutKey() feature is used, aggregates can't rehydrate themselves correctly. Mostly leaving this here as a reminder to come back to it.

**Comment by nunomaduro** [comment]
Thanks, meanwhile can you explain me what do you mean by `rehydrate themselves correctly`?

**Comment by nunomaduro** [comment]
Great news! This issue can be closed right?

**Comment by dexbytesmanish** [comment]
How to deal with pagination in aggregate mode ?

**Comment by nunomaduro** [comment]
@dexbytesmanish Can you write pseudo code to explain what you are trying to accomplish ?

**Comment by dexbytesmanish** [comment]
As per your repo example How do I perform paginate only Event or Article
model :

$models = App\Search\News::search('Laravel')->get();echo
get_class($models[0]); // "App\Article"echo get_class($models[1]); //
"App\Event"


How do I paginate $models[0]->paginate(2) ? // Article only

**Comment by jimbojsb** [comment]
It seems to me that use case defeats the point of using an aggregator in the first place.

**Comment by dexbytesmanish** [comment]
You mean I can't use aggregate for individual model pagination ?

**Comment by nunomaduro** [comment]
I am so sorry, maybe I am see it wrong. But I still didn't understand what you are trying to accomplish.

**Comment by dexbytesmanish** [comment]
If I do $news = App\Search\News::search('Star Trek')->paginate(15); it will
paginate all of the models/indices under News Model/Aggregated Index  I
want to paginate only any one Model/Index (Event/Article) at a time rather
than paginiating all (rest of) the Models/Indices.

**Comment by nunomaduro** [comment]
If you want to paginate the `App\Event`, you can just do: `App\Event::search('Star Trek')->paginate(15)` right?

**Comment by dexbytesmanish** [comment]
ok, I will try that but it should be same and single API call which will
also search other Models/Indices (of aggregator) if not searched earlier
and recently added to search query when paginate to single index/model
(Event) was performed with search.
