### ISSUE TITLE
How many models an aggregate can consist of ?

### ISSUE THREAD

**Issue by borealsmith** [algolia/scout-extended#70]
Hi,
I was wondering if there is a limit for the number of models an aggregate can consist of ?
Thanks.

**Comment by nunomaduro** [comment]
Hey @borealsmith 👋

Thanks for asking that.

At the moment, **there is no limit** on the number of models that can be aggregated.

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
