### ISSUE TITLE
aggregators indexing fails if SCOUT_QUEUE is true

### ISSUE THREAD

**Issue by jimbojsb** [algolia/scout-extended#72]
MakeSearchable job doesn't understand what to do with an Aggregator

**Comment by nunomaduro** [comment]
Thanks for reporting this issue @jimbojsb. I am going to take a look at this during the day!

**Comment by jimbojsb** [comment]
@nunomaduro Here's what I know: 

- The underling issue is that MakeSearchable has a collection of models as a property and that job uses SerializesModels. SerializesModels assumes that anything that is a collection is a collection of QueueableEntities, and will try to wakeup that collection by doing a database query by class and id of that entity. SerializesModels serializes the Aggregator classname but the ID of the model within the Aggregator, such that there is no way to actually unserialize that from a database correctly. 

The path I was working on to fix this requires overriding quite a bit of things. Without needing to modify Scout itself, I believe it requires a custom collection object that has a custom searchable macro that dispatches a custom job, which then has overrides for SerializesModels such that it can wake up a collection of Aggregators properly.

**Comment by jimbojsb** [comment]
Actually upon further investigation, I think this would require overriding the SearchableScope as well.

**Comment by nunomaduro** [comment]
@jimbojsb Thanks for the investigation, I will check this during the day of **tomorrow**, I am sure we will be able to fix this.

**Comment by nunomaduro** [comment]
@jimbojsb I may have found a solution for this issue: https://github.com/algolia/scout-extended/pull/77. Can you take a look?

**Comment by nunomaduro** [comment]
This issue has been fixed on the version `v0.4.0`.
