### ISSUE TITLE
Where condition on multidimensional arrray or nested object

### ISSUE THREAD

**Issue by yongkylie** [algolia/scout-extended#94]
Is it possible to do a search with `where` condition on a model that has multidimensional array or nested object?

Here is an example of `Student` index's structure stored in Algolia:
```
{
    'name': 'John Doe',
    'score': [
        {'subject': 'math', 'score': '85'},
        {'subject': 'spanish', 'score': '75'},
        ...
    ],
}
```

From above example, I need to do `search` everyone who has score more than 75 in math.
Thanks!

**Comment by yongkylie** [comment]
@nunomaduro I use Scout Extended configuration and doing all the filters on the back.
So, by using `toSearchableArray()` do you mean to change my index's structure into these formats below?

```
{
    'name': 'John Doe',
    'subjectScoreMath': 75,
    'subjectScoreSpanish': 65,
    ...
}
```

Thanks!

**Comment by nunomaduro** [comment]
@yongkylie Perfect. Exacly that! 

Then you just have todo:
```php
$models = Persons::search('query')->where('subjectSpanishScore', '>', 65)->get();
```

**Comment by yongkylie** [comment]
Thanks! I will close this issue for now.

**Comment by nunomaduro** [comment]
@yongkylie Happy to see that you have found a solution.

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
