### ISSUE TITLE
Eager loading for model resolution

### ISSUE THREAD

**Issue by fitztrev** [algolia/scout-extended#97]
When I switched from `laravel/scout` to `algolia/scout-extended` I noticed the model resolution is no longer eager loaded.

```php
Item::search('term')->get();
```

If the above search results in 20 items, there are 20 database queries. In `laravel/scout`, it would do one `where in (...)`.

**Comment by nunomaduro** [comment]
Thanks for reporting this, currently looking into it.

**Comment by nunomaduro** [comment]
This issue was being fixed on the version `v0.4.2`. Can you update it using `composer update algolia/scout-extended` and run a quick test?

**Comment by fitztrev** [comment]
Upgraded and confirmed fixed. Thank you!

**Comment by nunomaduro** [comment]
Thanks for the feedback on this!

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
