### ISSUE TITLE
Search behavior difference from Scout

### ISSUE THREAD

**Issue by fitztrev** [algolia/scout-extended#98]
I noticed another issue which would be a breaking change when switching from `scout` to `scout-extended`.

### Scenario:

The `items` index has 10 records.

### Issue:

With `laravel/scout`:

```php
count(Item::search('')->get())   // === 10
count(Item::search(null)->get()) // === 10
```

With `algolia/scout-extended`:

```php
count(Item::search('')->get()),  // === 10
count(Item::search(null)->get()) // === 0
```

This would be an issue because of Laravel's `ConvertEmptyStringsToNull` middleware. Like in my case, if someone is trying to do `Item::search($request->query)->get()`, they wouldn't get any results.

**Comment by nunomaduro** [comment]
This is weird, what version of Laravel Scout you were using before?

**Comment by fitztrev** [comment]
Just reverted back to the latest version of Scout to test:

```php
// laravel/scout@6.1.3 + algolia/algoliasearch-client-php@1.28.0
Item::search('')->raw()['nbHits'],  // === 10
Item::search(null)->raw()['nbHits'] // === 10

// algolia/scout-extended@0.4.2 + algolia/algoliasearch-client-php@2.1.1
Item::search('')->raw()['nbHits'],  // === 10
Item::search(null)->raw()['nbHits'] // === 0
```

**Comment by nunomaduro** [comment]
This issue was been fixed on the version `v0.4.3`. Can you update it using `composer update algolia/scout-extended` and run a quick test?

**Comment by fitztrev** [comment]
Working now in `v0.4.3`. Thanks!

**Comment by nunomaduro** [comment]
Thanks for the feedback on this!

_Be sure to stay tuned to my twitter account [@enunomaduro](http://twitter.com/enunomaduro) for more information about this package. Are you enjoying this package? Please tweet the link [https://github.com/algolia/scout-extended](https://github.com/algolia/scout-extended) and tells us your favourite feature!_ 🚀
